# Generated by Django 5.2.13 on 2026-05-21 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caixa', '0001_initial'),
        ('clientes', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total')),
                ('entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Entrada')),
                ('quantidade_parcelas', models.IntegerField(verbose_name='Quantidade de parcelas')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da parcela')),
                ('dia_vencimento', models.IntegerField(verbose_name='Dia de vencimento')),
                ('taxa_juros', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa de juros (% a.m.)')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Emissão')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('QUITADO', 'Quitado'), ('CANCELADO', 'Cancelado'), ('RENEGOCIADO', 'Renegociado')], default='ATIVO', max_length=12, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('carne_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renegociacoes', to='carne.carne', verbose_name='Carnê original (renegociação)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Carnê',
                'verbose_name_plural': 'Carnês',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaCarne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número da parcela')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor original')),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros')),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor pago')),
                ('data_vencimento', models.DateField(verbose_name='Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('forma_pagamento', models.CharField(blank=True, max_length=30, verbose_name='Forma de pagamento')),
                ('carne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='carne.carne')),
                ('sessao_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caixa.sessaocaixa', verbose_name='Sessão de caixa')),
                ('usuario_baixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Baixado por')),
            ],
            options={
                'verbose_name': 'Parcela do Carnê',
                'verbose_name_plural': 'Parcelas do Carnê',
                'ordering': ['numero'],
            },
        ),
        migrations.AddIndex(
            model_name='carne',
            index=models.Index(fields=['cliente', 'status'], name='carne_carne_cliente_614d86_idx'),
        ),
        migrations.AddIndex(
            model_name='carne',
            index=models.Index(fields=['status', 'criado_em'], name='carne_carne_status_36ccb4_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelacarne',
            index=models.Index(fields=['status', 'data_vencimento'], name='carne_parce_status_f00cb4_idx'),
        ),
    ]
