# Generated by Django 5.2.13 on 2026-05-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(default='Minha Loja', max_length=200, verbose_name='Nome fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=200, verbose_name='Razão social')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='Inscrição estadual')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Logo')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('pix_chave', models.CharField(blank=True, max_length=100, verbose_name='Chave PIX')),
                ('pix_tipo', models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('EMAIL', 'E-mail'), ('CELULAR', 'Celular'), ('ALEATORIA', 'Aleatória')], max_length=20, verbose_name='Tipo PIX')),
                ('banco_nome', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('banco_agencia', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('banco_conta', models.CharField(blank=True, max_length=30, verbose_name='Conta')),
                ('taxa_juros_mes', models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Juros ao mês (%)')),
                ('percentual_multa', models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Multa por atraso (%)')),
                ('carencia_juros_dias', models.IntegerField(default=3, verbose_name='Dias de carência antes de juros')),
                ('dias_alerta_vencimento', models.IntegerField(default=3, verbose_name='Alertar vencimentos com X dias de antecedência')),
                ('vender_sem_estoque', models.BooleanField(default=False, verbose_name='Permitir venda com estoque zerado')),
                ('desconto_maximo', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Desconto máximo sem senha (%)')),
                ('forma_pagamento_padrao', models.CharField(blank=True, default='DINHEIRO', max_length=30, verbose_name='Forma de pagamento padrão')),
                ('imprimir_cupom_auto', models.BooleanField(default=False, verbose_name='Imprimir cupom automaticamente')),
                ('cupom_cabecalho', models.TextField(blank=True, verbose_name='Cabeçalho do cupom')),
                ('cupom_rodape', models.TextField(blank=True, default='Obrigado pela preferência!\nVolte sempre!', verbose_name='Rodapé do cupom')),
                ('tema_cor', models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('red', 'Vermelho'), ('purple', 'Roxo'), ('orange', 'Laranja'), ('teal', 'Verde-azulado')], default='blue', max_length=20, verbose_name='Cor principal')),
                ('modo_escuro', models.BooleanField(default=False, verbose_name='Modo escuro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Loja',
                'verbose_name_plural': 'Configurações da Loja',
            },
        ),
    ]
