# Generated by Django 5.2.13 on 2026-05-21 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caixa', '0001_initial'),
        ('clientes', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da venda')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de entrega')),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor dos produtos')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto (R$)')),
                ('percentual_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto (%)')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor pago')),
                ('valor_troco', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Troco')),
                ('valor_pendente', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor pendente')),
                ('status', models.CharField(choices=[('ORCAMENTO', 'Orçamento'), ('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('PARCIAL', 'Parcialmente Pago'), ('CANCELADO', 'Cancelado'), ('DEVOLVIDO', 'Devolvido')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('canal', models.CharField(choices=[('LOJA', 'Loja Física'), ('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('SITE', 'Site'), ('TELEFONE', 'Telefone')], default='LOJA', max_length=10, verbose_name='Canal')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('observacoes_internas', models.TextField(blank=True, verbose_name='Observações internas')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='Motivo do cancelamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caixa.sessaocaixa')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_canceladas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CHEQUE', 'Cheque'), ('TRANSFERENCIA', 'Transferência'), ('CREDIARIO', 'Crediário'), ('CARNE', 'Carnê'), ('VALE', 'Vale/Crédito')], max_length=20, verbose_name='Forma')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('parcelas', models.IntegerField(default=1, verbose_name='Parcelas')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('nsu', models.CharField(blank=True, max_length=30, verbose_name='NSU (cartão)')),
                ('bandeira', models.CharField(blank=True, max_length=30, verbose_name='Bandeira')),
                ('vencimento_cheque', models.DateField(blank=True, null=True, verbose_name='Vencimento do cheque')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/', verbose_name='Comprovante')),
                ('observacoes', models.CharField(blank=True, max_length=200, verbose_name='Observações')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Pagamento de Venda',
                'verbose_name_plural': 'Pagamentos de Venda',
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto (%)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comissão (%)')),
                ('comissao_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão (R$)')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.gradeproduto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Venda',
            },
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['status', 'data_venda'], name='vendas_vend_status_4e49dc_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['cliente', 'status'], name='vendas_vend_cliente_ee5974_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['numero'], name='vendas_vend_numero_03706f_idx'),
        ),
    ]
