# Generated by Django 5.2.13 on 2026-05-21 13:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['first_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('master', 'Master (Dono)'), ('gerente', 'Gerente'), ('caixa', 'Operador de Caixa'), ('estoquista', 'Estoquista'), ('financeiro', 'Financeiro')], default='caixa', max_length=20, verbose_name='Cargo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Foto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('acesso_funcionarios', models.BooleanField(default=False, verbose_name='Funcionários')),
                ('acesso_clientes', models.BooleanField(default=True, verbose_name='Clientes')),
                ('acesso_fornecedores', models.BooleanField(default=False, verbose_name='Fornecedores')),
                ('acesso_produtos', models.BooleanField(default=False, verbose_name='Produtos')),
                ('acesso_estoque', models.BooleanField(default=False, verbose_name='Estoque')),
                ('acesso_compras', models.BooleanField(default=False, verbose_name='Compras')),
                ('acesso_vendas', models.BooleanField(default=True, verbose_name='Vendas')),
                ('acesso_caixa', models.BooleanField(default=True, verbose_name='Caixa')),
                ('acesso_financeiro', models.BooleanField(default=False, verbose_name='Financeiro')),
                ('acesso_carne', models.BooleanField(default=True, verbose_name='Carnê')),
                ('acesso_relatorios', models.BooleanField(default=False, verbose_name='Relatórios')),
                ('acesso_configuracoes', models.BooleanField(default=False, verbose_name='Configurações')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='TentativaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Usuário')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('tentativas', models.IntegerField(default=0, verbose_name='Tentativas')),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado até')),
                ('ultima_tentativa', models.DateTimeField(auto_now=True, verbose_name='Última tentativa')),
            ],
            options={
                'verbose_name': 'Tentativa de Login',
                'verbose_name_plural': 'Tentativas de Login',
                'unique_together': {('username', 'ip')},
            },
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CRIAR', 'Criar'), ('EDITAR', 'Editar'), ('EXCLUIR', 'Excluir'), ('VISUALIZAR', 'Visualizar'), ('EXPORTAR', 'Exportar'), ('IMPRIMIR', 'Imprimir'), ('CANCELAR', 'Cancelar'), ('BAIXAR', 'Baixar Pagamento')], max_length=20, verbose_name='Ação')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('objeto_id', models.CharField(blank=True, max_length=50, verbose_name='ID do Objeto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', 'criado_em'], name='autenticaca_usuario_b40ac7_idx'), models.Index(fields=['modelo', 'objeto_id'], name='autenticaca_modelo_bb9b87_idx')],
            },
        ),
    ]
