# Generated by Django 5.2.13 on 2026-05-21 13:11

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[apps.core.validators.cpf_validator], verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO', 'União Estável')], max_length=15, verbose_name='Estado civil')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='funcionarios/', verbose_name='Foto')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('setor', models.CharField(blank=True, max_length=100, verbose_name='Setor')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comissão (%)')),
                ('data_admissao', models.DateField(verbose_name='Data de admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de demissão')),
                ('tipo_contrato', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('EST', 'Estágio'), ('AUT', 'Autônomo')], default='CLT', max_length=3, verbose_name='Tipo de contrato')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=30, verbose_name='Conta')),
                ('tipo_conta', models.CharField(blank=True, choices=[('CC', 'Corrente'), ('CP', 'Poupança')], max_length=2, verbose_name='Tipo de conta')),
                ('pix', models.CharField(blank=True, max_length=100, verbose_name='Chave PIX')),
                ('ctps_numero', models.CharField(blank=True, max_length=20, verbose_name='CTPS Número')),
                ('ctps_serie', models.CharField(blank=True, max_length=10, verbose_name='CTPS Série')),
                ('pis_pasep', models.CharField(blank=True, max_length=20, verbose_name='PIS/PASEP')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do sistema')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='FeriasFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FERIAS', 'Férias'), ('LICENCA', 'Licença Médica'), ('MATERNIDADE', 'Licença Maternidade'), ('AFASTAMENTO', 'Afastamento')], default='FERIAS', max_length=15, verbose_name='Tipo')),
                ('data_inicio', models.DateField(verbose_name='Início')),
                ('data_fim', models.DateField(verbose_name='Fim')),
                ('dias', models.IntegerField(default=0, verbose_name='Dias')),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM_CURSO', 'Em Curso'), ('CONCLUIDO', 'Concluído')], default='AGENDADO', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Férias/Afastamento',
                'verbose_name_plural': 'Férias/Afastamentos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário anterior')),
                ('salario_novo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário novo')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('data_alteracao', models.DateField(auto_now_add=True, verbose_name='Data da alteração')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_salarios', to='funcionarios.funcionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
            ],
            options={
                'verbose_name': 'Histórico de Salário',
                'verbose_name_plural': 'Históricos de Salário',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['cpf'], name='funcionario_cpf_dc5eae_idx'),
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['ativo', 'cargo'], name='funcionario_ativo_29a527_idx'),
        ),
    ]
