# Generated by Django 5.2.13 on 2026-05-21 13:11

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[apps.core.validators.cpf_validator], verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('razao_social', models.CharField(blank=True, max_length=200, verbose_name='Razão social')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[apps.core.validators.cnpj_validator], verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='Inscrição estadual')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome fantasia')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Limite de crédito')),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo devedor')),
                ('dia_vencimento', models.IntegerField(blank=True, null=True, verbose_name='Dia de vencimento padrão')),
                ('categoria', models.CharField(choices=[('REGULAR', 'Regular'), ('VIP', 'VIP'), ('ATACADO', 'Atacado'), ('INADIMPLENTE', 'Inadimplente')], default='REGULAR', max_length=15, verbose_name='Categoria')),
                ('pontos_fidelidade', models.IntegerField(default=0, verbose_name='Pontos de fidelidade')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='clientes/', verbose_name='Foto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['cpf'], name='clientes_cl_cpf_e6905f_idx'), models.Index(fields=['cnpj'], name='clientes_cl_cnpj_db43af_idx'), models.Index(fields=['celular'], name='clientes_cl_celular_693504_idx'), models.Index(fields=['ativo', 'categoria'], name='clientes_cl_ativo_696e7a_idx')],
            },
        ),
    ]
