# Generated by Django 5.2.13 on 2026-05-21 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('compras', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=30, verbose_name='Conta')),
                ('tipo', models.CharField(choices=[('CORRENTE', 'Corrente'), ('POUPANCA', 'Poupança'), ('CAIXA', 'Caixa Físico'), ('PIX', 'Conta PIX')], default='CORRENTE', max_length=10, verbose_name='Tipo')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo inicial')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='financeiro.planocontas', verbose_name='Conta pai')),
            ],
            options={
                'verbose_name': 'Plano de Contas',
                'verbose_name_plural': 'Planos de Contas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('data_competencia', models.DateField(verbose_name='Competência')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Pagamento')),
                ('status', models.CharField(choices=[('PREVISTO', 'Previsto'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='PREVISTO', max_length=10, verbose_name='Status')),
                ('recorrente', models.BooleanField(default=False, verbose_name='Recorrente')),
                ('recorrencia', models.CharField(blank=True, choices=[('MENSAL', 'Mensal'), ('SEMANAL', 'Semanal'), ('ANUAL', 'Anual')], max_length=10, verbose_name='Recorrência')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='lancamentos/', verbose_name='Anexo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.contabancaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plano_contas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.planocontas', verbose_name='Plano de contas')),
            ],
            options={
                'verbose_name': 'Lançamento Financeiro',
                'verbose_name_plural': 'Lançamentos Financeiros',
                'ordering': ['-data_competencia'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor original')),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros')),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor pago')),
                ('valor_pendente', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor pendente')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('PARCIAL', 'Parcialmente Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('forma_pagamento', models.CharField(blank=True, max_length=30, verbose_name='Forma de pagamento')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/', verbose_name='Comprovante')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('parcela_numero', models.IntegerField(default=1, verbose_name='Parcela nº')),
                ('parcela_total', models.IntegerField(default=1, verbose_name='Total de parcelas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.ordemcompra', verbose_name='Compra')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fornecedores.fornecedor', verbose_name='Fornecedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['data_vencimento'],
                'indexes': [models.Index(fields=['status', 'data_vencimento'], name='financeiro__status_7acc63_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor original')),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros')),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor pago')),
                ('valor_pendente', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor pendente')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('PARCIAL', 'Parcialmente Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('forma_recebimento', models.CharField(blank=True, max_length=30, verbose_name='Forma de recebimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('parcela_numero', models.IntegerField(default=1, verbose_name='Parcela nº')),
                ('parcela_total', models.IntegerField(default=1, verbose_name='Total de parcelas')),
                ('carne_grupo', models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='Grupo do carnê')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['data_vencimento'],
                'indexes': [models.Index(fields=['status', 'data_vencimento'], name='financeiro__status_f45da9_idx'), models.Index(fields=['cliente', 'status'], name='financeiro__cliente_62fae2_idx')],
            },
        ),
    ]
