# Generated by Django 5.2.13 on 2026-05-21 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque_sistema', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Estoque sistema')),
                ('estoque_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estoque contado')),
                ('divergencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Divergência')),
                ('ajustado', models.BooleanField(default=False, verbose_name='Ajustado')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.gradeproduto')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.inventario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra'), ('ENTRADA_DEVOLUCAO', 'Entrada por Devolução'), ('ENTRADA_AJUSTE', 'Entrada por Ajuste'), ('SAIDA_VENDA', 'Saída por Venda'), ('SAIDA_DEVOLUCAO', 'Saída Devolução a Fornecedor'), ('SAIDA_AJUSTE', 'Saída por Ajuste'), ('SAIDA_PERDA', 'Saída por Perda/Avaria'), ('TRANSFERENCIA', 'Transferência')], max_length=20, verbose_name='Tipo')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo unitário')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo anterior')),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo atual')),
                ('referencia_id', models.IntegerField(blank=True, null=True, verbose_name='ID da referência')),
                ('referencia_tipo', models.CharField(blank=True, max_length=50, verbose_name='Tipo da referência')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.gradeproduto', verbose_name='Grade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='Produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['produto', 'criado_em'], name='estoque_mov_produto_f9950a_idx'), models.Index(fields=['tipo', 'criado_em'], name='estoque_mov_tipo_bc352d_idx')],
            },
        ),
    ]
