# Generated by Django 5.2.13 on 2026-05-21 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('codigo_hex', models.CharField(blank=True, max_length=7, verbose_name='Cor (hex)')),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('tipo', models.CharField(choices=[('ADULTO', 'Adulto'), ('INFANTIL', 'Infantil'), ('NUMERICO', 'Numérico')], default='ADULTO', max_length=10, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
                'ordering': ['tipo', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código de barras')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referência')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('SIMPLES', 'Simples'), ('GRADE', 'Com Grade (cor/tamanho)'), ('KIT', 'Kit/Composição')], default='SIMPLES', max_length=10, verbose_name='Tipo')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de custo')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margem de lucro (%)')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de venda')),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço promocional')),
                ('promocao_inicio', models.DateField(blank=True, null=True, verbose_name='Início da promoção')),
                ('promocao_fim', models.DateField(blank=True, null=True, verbose_name='Fim da promoção')),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque atual')),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque mínimo')),
                ('estoque_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque máximo')),
                ('unidade', models.CharField(default='UN', max_length=10, verbose_name='Unidade')),
                ('localizacao', models.CharField(blank=True, max_length=50, verbose_name='Localização (prateleira)')),
                ('ncm', models.CharField(blank=True, max_length=10, verbose_name='NCM')),
                ('cest', models.CharField(blank=True, max_length=9, verbose_name='CEST')),
                ('cfop', models.CharField(blank=True, max_length=4, verbose_name='CFOP')),
                ('origem', models.CharField(choices=[('0', 'Nacional'), ('1', 'Estrangeira')], default='0', max_length=1, verbose_name='Origem')),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Foto principal')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.categoria', verbose_name='Categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço anterior')),
                ('preco_novo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço novo')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/fotos/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=100, verbose_name='Legenda')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Foto do Produto',
                'verbose_name_plural': 'Fotos dos Produtos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='produtos.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.subcategoria', verbose_name='Subcategoria'),
        ),
        migrations.CreateModel(
            name='GradeProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código de barras')),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço adicional')),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.cor', verbose_name='Cor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='produtos.produto')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.tamanho', verbose_name='Tamanho')),
            ],
            options={
                'verbose_name': 'Grade do Produto',
                'verbose_name_plural': 'Grades dos Produtos',
                'ordering': ['tamanho__ordem', 'cor__nome'],
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['codigo'], name='produtos_pr_codigo_0900e1_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['codigo_barras'], name='produtos_pr_codigo__f87624_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ativo', 'categoria'], name='produtos_pr_ativo_68fd0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeproduto',
            unique_together={('produto', 'cor', 'tamanho')},
        ),
    ]
