# Generated by Django 5.2.13 on 2026-05-21 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('data_pedido', models.DateField(auto_now_add=True, verbose_name='Data do pedido')),
                ('data_previsao', models.DateField(blank=True, null=True, verbose_name='Previsão de entrega')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de recebimento')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado ao Fornecedor'), ('PARCIAL', 'Recebido Parcialmente'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=10, verbose_name='Status')),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor dos produtos')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do frete')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('condicao_pagamento', models.CharField(blank=True, max_length=100, verbose_name='Condição de pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('nf_numero', models.CharField(blank=True, max_length=20, verbose_name='Número da NF')),
                ('nf_arquivo', models.FileField(blank=True, null=True, upload_to='nfs/', verbose_name='Arquivo da NF')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fornecedores.fornecedor', verbose_name='Fornecedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Ordem de Compra',
                'verbose_name_plural': 'Ordens de Compra',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_pedida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qtd pedida')),
                ('quantidade_recebida', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qtd recebida')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto (%)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.gradeproduto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.ordemcompra')),
            ],
            options={
                'verbose_name': 'Item da Ordem de Compra',
                'verbose_name_plural': 'Itens da Ordem de Compra',
            },
        ),
        migrations.AddIndex(
            model_name='ordemcompra',
            index=models.Index(fields=['status', 'data_pedido'], name='compras_ord_status_a9bff8_idx'),
        ),
    ]
