# Generated by Django 5.2.13 on 2026-05-21 13:11

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('PF', 'Pessoa Física')], default='PJ', max_length=2, verbose_name='Tipo')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão social / Nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[apps.core.validators.cnpj_validator], verbose_name='CNPJ')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[apps.core.validators.cpf_validator], verbose_name='CPF')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='Inscrição estadual')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('prazo_pagamento', models.IntegerField(default=30, verbose_name='Prazo de pagamento (dias)')),
                ('condicao_pagamento', models.CharField(blank=True, max_length=100, verbose_name='Condição de pagamento')),
                ('desconto_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto padrão (%)')),
                ('avaliacao', models.IntegerField(blank=True, choices=[(1, '★ Ruim'), (2, '★★ Regular'), (3, '★★★ Bom'), (4, '★★★★ Muito Bom'), (5, '★★★★★ Excelente')], null=True, verbose_name='Avaliação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['razao_social'],
                'indexes': [models.Index(fields=['cnpj'], name='fornecedore_cnpj_a9fb5e_idx'), models.Index(fields=['ativo'], name='fornecedore_ativo_602a05_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContatoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('principal', models.BooleanField(default=False, verbose_name='Contato principal')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='fornecedores.fornecedor')),
            ],
            options={
                'verbose_name': 'Contato do Fornecedor',
                'verbose_name_plural': 'Contatos dos Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='AnexoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='fornecedores/anexos/', verbose_name='Arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='fornecedores.fornecedor')),
            ],
            options={
                'verbose_name': 'Anexo do Fornecedor',
                'verbose_name_plural': 'Anexos dos Fornecedores',
            },
        ),
    ]
