# Generated by Django 5.2.13 on 2026-05-21 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='SessaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Abertura')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Fechamento')),
                ('valor_abertura', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de abertura')),
                ('valor_suprimento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Suprimentos')),
                ('valor_sangria', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sangrias')),
                ('total_dinheiro', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Dinheiro')),
                ('total_pix', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total PIX')),
                ('total_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Crédito')),
                ('total_debito', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Débito')),
                ('total_crediario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Crediário')),
                ('total_outros', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Outros')),
                ('total_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Vendas')),
                ('valor_contado_dinheiro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dinheiro contado')),
                ('diferenca_caixa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferença')),
                ('observacoes_fechamento', models.TextField(blank=True, verbose_name='Observações do fechamento')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='caixa.caixa')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Sessão de Caixa',
                'verbose_name_plural': 'Sessões de Caixa',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ABERTURA', 'Abertura'), ('SUPRIMENTO', 'Suprimento'), ('SANGRIA', 'Sangria'), ('RECEBIMENTO', 'Recebimento'), ('PAGAMENTO', 'Pagamento'), ('VENDA', 'Venda'), ('DEVOLUCAO', 'Devolução')], max_length=15, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referência')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='caixa.sessaocaixa')),
            ],
            options={
                'verbose_name': 'Movimentação de Caixa',
                'verbose_name_plural': 'Movimentações de Caixa',
                'ordering': ['-criado_em'],
            },
        ),
    ]
